apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: todo-app
data:
  DB_HOST:     mysql-service
  DB_PORT:     "3306"
  DB_USER:     todo_user
  DB_NAME:     todo_db
  PORT:        "3000"
  CORS_ORIGIN: "http://todo-frontend-service"
